server:
   port: 9090

spring:
  datasource:
      url:  jdbc:postgresql://localhost:8080/Proyecto1
      username: postgres
      password: Edmilzon890
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
